---
qdts_version: 0.1.0
config:
  application_interface: etsi-gs-qkd-004
  qkd_protocol: e91
nodes:
  - node_name: munich
    node_ip: 192.168.5.10
    neighbour_nodes:
      - nuremberg
  - node_name: nuremberg
    node_ip: 192.168.5.20
    neighbour_nodes:
      - munich
  