---
qdts_version: 0.1.0
config:
  application_interface: etsi-gs-qkd-004
  qkd_protocol: e91
nodes:
  - node_name: sevilla
    node_ip: 192.168.7.10
    neighbour_nodes:
      - huelva
      - cadiz
  - node_name: huelva
    node_ip: 192.168.7.20
    neighbour_nodes:
      - sevilla
      - cadiz
  - node_name: cadiz
    node_ip: 192.168.7.30
    neighbour_nodes:
      - sevilla
      - huelva
  